window:
  padding:
    x: 30
    y: 30
font:
  size: 12.0
  normal:
    family: Fira Code
    style: Medium
  bold:
    family: Fira Code
  italic:
    family: Fira Code
colors:
  primary:
    background: '0x020e16'
    foreground: '0xcecece'
  # Normal colors
  normal:
    black:   '0x020e16'
    red:     '0xb64a51'
    green:   '0x4a9c66'
    yellow:  '0xf38f63'
    blue:    '0x446ea6'
    magenta: '0x956ba2'
    cyan:    '0x53a3b7'
    white:   '0xcecece'

  # Bright colors
  bright:
    black:   '0x020e16'
    red:     '0xf3636c'
    green:   '0x5fc883'
    yellow:  '0xffbf47'
    blue:    '0x598fd8'
    magenta: '0xc38cd5'
    cyan:    '0x6ad0ea'
    white:   '0xffffff'
cursor:
  style: Beam
key_bindings:
  # (Windows, Linux, and BSD only)
  - { key: V,        mods: Control, action: Paste            }
debug:
  persistent_logging: false
  log_level: Debug
