window:
  padding:
    x: 30
    y: 30
font:
  size: 12.0
  normal:
    family: Source Code Pro
    style: Medium
  bold:
    family: Source Code Pro
  italic:
    family: Source Code Pro
colors:
  primary:
    background: '0x1a1a1a'
    foreground: '0xf2f2f2'
  # Normal colors
  normal:
    black:   '0x1a1a1a'
    red:     '0xff4949'
    green:   '0x64e66f'
    yellow:  '0xffdf40'
    blue:    '0x3991ea'
    magenta: '0xdc76ff'
    cyan:    '0x3cc1e5'
    white:   '0xf2f2f2'

  # Bright colors
  bright:
    black:   '0x424242'
    red:     '0xff4646'
    green:   '0x78dc60'
    yellow:  '0xf0c542'
    blue:    '0x53a9ff'
    magenta: '0xc859ed'
    cyan:    '0x2ed2ff'
    white:   '0xf2f2f2'
cursor:
  style: Beam
key_bindings:
  # (Windows, Linux, and BSD only)
  - { key: V,        mods: Control, action: Paste            }
debug:
  persistent_logging: false
  log_level: Debug
