"ui.background" = "black"
"ui.text" = "white"
"ui.selection" = { bg = "light-gray" }
"ui.linenr" = "gray"
"ui.text.info" = "magenta"
"ui.statusline" = "magenta"

comment = "gray"
"function" = "blue"
"function.macro" = "magenta"
"keyword" = "magenta"
"type" = "light-yellow"
"type.builtin" = "yellow"
"constant" = "yellow"
"constant.character.escape" = "red"
"string" = "light-green"
"variable.builtin" = "yellow"
"operator" = "cyan"
"keyword.storage.modifier" = "yellow"

"markup.heading" = "cyan"
"markup.italic" = { modifiers=["italic"] }
"markup.bold" = { modifiers=["bold"] }

"diagnostic" = { modifiers = ["underlined"]}
"error" = "red"
"warning" = "yellow"
"info" = "cyan"

[pallete]
white = "#f2f2f2"
black = "#1a1a1a"
red = "#dd4e4e"
green = "#6e9f57"
yellow = "#de8b50"
blue = "#5b8bd6"
magenta = "#a56cc4"
cyan = "#72c2c4"
gray = "#424242"
light-red = "#f35656"
light-green = "#83bd68"
light-yellow = "#f0cb74"
light-blue = "#689ef3"
light-magenta = "#c782ec"
light-cyan = "#72c2c4"
light-gray = "#d2d2d2"

